### ISSUE TITLE
[BE] 백엔드 초기 환경을 구성한다.

### ISSUE THREAD

**Issue by 2yujeong** [woowacourse-teams/2022-levellog#1]
## 목적
레벨로그 백엔드 개발을 위한 환경설정

## 작업 상세 내용
- [x] 스프링 프로젝트 생성

**Comment by SuyeonChoi** [comment]
## 기술 스택 
- Java 11
- SpringBoot 2.7.1
- JPA + Spring Data JPA
- Lombok
- MariaDB Driver

**Comment by SuyeonChoi** [comment]
폴더 구조좀 바꿔볼게요~!

**Comment by yunjin-kim** [comment]
밑에 간단하게 설명 적어주실 수 있나요 🤩
