### ISSUE TITLE
[BE] 검증 로직이 포함된 도메인의 @AllArgsConstructor 대신 직접 생성자를 생성하도록 수정한다.

### ISSUE THREAD

**Issue by OzRagwort** [woowacourse-teams/2022-levellog#100]
## 목적
- 검증 로직이 포함된 도메인에서 `@AllArgsConstructor`대신 직접 생성자를 만들어서 검증을 할 수 있도록 하기 위해서

## 작업 상세 내용
- [ ] 검증 로직이 포함된 도메인의 `@AllArgsConstructor`를 제거하고 직접 생성자를 생성

**Comment by kbsat** [comment]
도메인에서 어느정도로 검증을 할 지에 대한 고민을 함께 해보면 좋을 것 같다.
