### ISSUE TITLE
[BE] 테스트 코드 네이밍 컨벤션 수정

### ISSUE THREAD

**Issue by OzRagwort** [woowacourse-teams/2022-levellog#124]
## 목적
테스트 메서드의 네이밍 컨벤션을 통일시킨다 

## 작업 상세 내용
- [x] 모든 테스트 메서드의 네이밍 컨벤션을 통일시킨다
- [x] 스니펫의 네이밍 컨벤션을 통일시킨다

**Comment by kbsat** [comment]
### 스니펫 규칙
- 기본적으로 **케밥 케이스**를 유지한다.
  - ✅ `interview-question/delete`
  - ❌ `interviewQuestion/delete"`
- 예외의 경우 다음과 같이 이름을 짓는다
  - ✅ `interview-question/delete/exception/not-found`
  - ❌ `interview-question/delete-exception-not-found`
- exception 하위에 하위 클래스를 두지 않는다.
  - ✅ `team/update/exception/title-length`
  - ❌ `team/update/exception/title/length`

🫡 **위 규칙을 만족하도록 기존 테스트를 수정하였습니다.**
- 추가적으로 null-and-blank 라는 스니펫을 많이 있었는데 좀 어색해서 blank 라는 이름으로 모두 수정했습니다.
  - blank 안에 null or blank 의미가 포함되있기 때문

**Comment by kbsat** [comment]
### 테스트코드 네이밍 
- Nested class 의 이름은 테스트하려는 메서드 이름으로 한다.
  - ✅`class FindAll{ }`
  - ❌`class FindAllTest{ }`
  - ❌`class findAll{ }`
- 만일 Nested class로 분리되었을 때 단일 성공 케이스를 검사할 경우에는 `success()` 로 네이밍한다.
  - 단일 성공 케이스만 있는게 아니라면 `method이름_성공상황_success` 로 네이밍한다.
- Nested Class로 분리하지 않고 성공 케이스만 검사할 경우에는 해당 메서드 이름을 카멜케이스로 네이밍한다. `findAllByLevellog()`
- 예외 테스트 메서드 명은 `method이름_예외상황_exception` 으로 한다.
  - 각 단락은 항상 카멜케이스를 유지한다. ( 첫문자 소문자 )
  - ✅`update_nameNullOrEmpty_exception()`
  - ❌`Update_NameNullOrEmpty_Exception()`
  - ❌`update_nameNullOrEmpty_exceptionThrown()`
