### ISSUE TITLE
[BE] 새로운 컨벤션에 맞게 리팩터링한다.

### ISSUE THREAD

**Issue by SuyeonChoi** [woowacourse-teams/2022-levellog#127]
## 목적
- 새로운 팀 코드 컨벤션에 맞게 전반적인 코드를 리팩터링한다.
- 테스트와 방어 로직을 보강한다.

## 작업 상세 내용
- [x] [BE] 레벨로그 관련 코드를 리팩터링한다.
- [x] [BE] 팀 관련 코드를 리팩터링한다.
- [x] [BE] 멤버 관련 코드를 리팩터링한다.
- [x] [BE] 피드백 관련 코드를 리팩터링한다.
- [x] [BE] 인증 관련 코드를 리팩터링한다.

### 공통으로 지켜야할 컨벤션
- DTO 클래스명 변경
- DTO 정적 팩터리 메서드 추가(`new`로 생성 방지)
- 도메인 검증 로직 추가
  - 도메인 테스트 추가
- 서비스에서 `@Transactional` 추가하기
- 매개변수에서는 객체 ➡️ `id` 값들 순서
- 커스텀 예외에 대한 구체 메세지 작성
- 예외 로그에 많은 정보를 담되, 간단한 메세지로 표현
- 컨트롤러테스트에서 문서화를 위한 예외케이스를 추가 (Mocking)
- 서비스테스트 보강

## 참고사항
삭제 정책은 추후에 고려하도록 한다.

**Comment by SuyeonChoi** [comment]
릭 ➡️ 인증
로마 ➡️ 멤버
이브 ➡️ 피드백
알린 ➡️ 팀
페퍼 ➡️ 레벨로그

**Comment by nailseong** [comment]
close #100
