### ISSUE TITLE
[BUG] PR 템플릿이 적용되지 않는 이슈를 해결한다.

### ISSUE THREAD

**Issue by SuyeonChoi** [woowacourse-teams/2022-levellog#14]
## 버그 기능
- PR 템플릿이 적용되도록 수정한다.

### 현재 동작
PR 템플릿이 적용되지 않음
<img width="922" alt="image" src="https://user-images.githubusercontent.com/28749734/177498075-02bb91f7-82b5-436a-ba81-6be80b16fed4.png">

**Comment by kbsat** [comment]
해결했으니 클로즈 하겠습니다. ^.^
