### ISSUE TITLE
[FE] 팀 조회 API 변동에 대응한다.

### ISSUE THREAD

**Issue by frontend-jihyeok-um** [woowacourse-teams/2022-levellog#156]
## 목적
- 팀 조회시 `participants`의 `id`가 `memberId`로 바뀐 것에 대응한다.

## 작업 상세 내용
- [x] `participants`의 타입의 프로퍼티를 `id`에서 `memberId`로 변경한다.
- [x] `participants`를 사용하는 로직에서 `id`를 `memberId`로 변경한다.
  - [x] 컴포넌트들
  - [x] 커스텀 훅들
  - [x] API 함수들

**Comment by OzRagwort** [comment]
감사합니당
