### ISSUE TITLE
[BE] 컨트롤러 테스트를 리팩토링한다.

### ISSUE THREAD

**Issue by kbsat** [woowacourse-teams/2022-levellog#186]
## 목적
- 컨트롤러에서 모킹을 사용하기 때문에 특정 모킹(로그인) 혹은 상수(로그인토큰)가 반복되는 현상이 발생함.
- `doThrow`와 `given - willThrow`가 섞여서 나타나고있음 -> 형식의 통일 필요
- 컨트롤러 테스트를 리팩토링함으로써 앞으로 컨트롤러 테스트 작성에 용이함을 얻기 위함

## 작업 상세 내용
- [x] mockLogin을 `ControllerTest`에 구현하여 모든 컨트롤러 테스트에서 사용가능하도록 한다.
- [x] 로그인 토큰을 `ControllerTest`에 상수화하여 모든 컨트롤러 테스트에서 사용가능하도록 한다.
- [x] Throw 모킹 방식을 하나로 통일한다
- [x] 이 외 Controller 테스트를 리팩토링 하는 법에 대해 고민하여 적용한다.

**Comment by SuyeonChoi** [comment]
## 작업 내역
- `doThrow` ➡️ `given - willThrow` 
- `mockLogin`을 `ControllerTest`에서 구현함
- `@BeforeEach` 에서 `mockLogin()`을 호출함
  - 컨트롤러 테스트는 로그인에 대한 예외 테스트와 무관하고, 대부분의 API에서 로그인 인증이 필요함
- 기존 `@BeforeEach`의 RestDocs 관련 코드 메서드 추출  ➡️ `setMockMvcRestDocsSpec()`
- 컨트롤러 테스트 클래스/메서드 네이밍은 [#124](https://github.com/woowacourse-teams/2022-levellog/issues/124)  에서 다루기 때문에 고려하지 않음
