### ISSUE TITLE
[BUG] 팀 생성 시 내 이름이 출력되지 않는 문제를 해결한다.

### ISSUE THREAD

**Issue by OzRagwort** [woowacourse-teams/2022-levellog#210]
## 버그 기능
- 프론트) 팀 생성 페이지

### 버그 상황 재연
- 로그인 후 새로고침을 하지 않고 팀 생성을 하면 팀 생성 시 내 이름이 출력되지 않는다.

### 기대 동작
- 내 이름이 출력되어야 한다.

### 현재 동작
- 로그인 후 새로고침을 하지 않고 팀 생성을 하면 팀 생성 시 내 이름이 출력되지 않는다.

**Comment by frontend-jihyeok-um** [comment]
해결했습니다.
