### ISSUE TITLE
[FE] 레벨로그가 삭제가 되지않는 버그를 수정한다.

### ISSUE THREAD

**Issue by frontend-jihyeok-um** [woowacourse-teams/2022-levellog#229]
## 버그 기능
- 레벨로그가 삭제가 되지않는 버그를 수정한다.

### 버그 상황 재연
- 본인의 레벨로그를 삭제하려하면 "예상치 못한 예외가 발생했습니다." 라는 메시지와 함께 삭제에 실패한다.

### 기대 동작
- 레벨로그가 삭제된다.

### 현재 동작
- 본인의 레벨로그를 삭제하려하면 "예상치 못한 예외가 발생했습니다." 라는 메시지와 함께 삭제에 실패한다.

**Comment by frontend-jihyeok-um** [comment]
- 새로 추가하는 팀의 레벨로그는 삭제됌
- 더미데이터 팀의 레벨로그는 삭제 안 됌

**Comment by yunjin-kim** [comment]
백엔드 이슈여서 클로즈 하겠습니다
