### ISSUE TITLE
[BUG] 사전질문 혹은 피드백이 남겨진 레벨로그 삭제 시 예외가 발생하는 문제를 해결한다.

### ISSUE THREAD

**Issue by kbsat** [woowacourse-teams/2022-levellog#234]
## 버그 기능
- 사전질문 혹은 피드백이 남겨진 레벨로그를 삭제하려할 때 예외가 발생한다.

### 버그 상황 재연
- 레벨로그를 작성한다.
- 누군가 레벨로그에 사전질문, 피드백을 남긴다.
- 레벨로그 삭제 요청한다.

### 기대 동작
- 레벨로그가 삭제가 된다.

### 현재 동작
- 예상치못한 예외가 발생했습니다. alert 발생 <- 레벨로그를 id로 사용하고 있는 피드백, 사전질문 때문에 안지워짐
- 레벨로그가 삭제되었습니다. alert 발생 <- 실제로는 안지워진 상태

**Comment by nailseong** [comment]
#254 레벨로그 삭제 정책이 `삭제 불가능`으로 변경되어서 이슈 close합니다~ 😉
