### ISSUE TITLE
[BE] 레벨로그 상세 조회 시 body에 작성자의 정보도 준다.

### ISSUE THREAD

**Issue by kbsat** [woowacourse-teams/2022-levellog#249]
## 목적
- 피드백 작성 페이지에서 레벨로그 조회는 가능하지만 작성자에 대한 정보가 없어 타이틀의 메세지를 정해주기 어렵다.

## 작업 상세 내용
- [x] 레벨로그 상세조회 API의 반환을 변경한다.

## 참고사항
요런 느낌?
{
    "author": {
      "id" : 1,
      "nickname" : "eve1",
      "profileUrl" : "eve1.com"
      },
      "content" : "bmlbkfmbkl"
}

**Comment by OzRagwort** [comment]
찬성합니다
