### ISSUE TITLE
[FE] 레벨로그 삭제하는 기능을 제거한다.

### ISSUE THREAD

**Issue by yunjin-kim** [woowacourse-teams/2022-levellog#255]
## 목적
- 삭제 정책 변경으로 인하여

## 작업 상세 내용
- [ ] 레벨로그 삭제하는 기능을 제거한다.

**Comment by frontend-jihyeok-um** [comment]
이거 제가 하고있는 정책변경 반영에 포함되는 이슈 아닌가요?

**Comment by yunjin-kim** [comment]
@jihyeok-um  팀 관련 정책만 하는줄 알았네용 클로즈하겠습니다!
