### ISSUE TITLE
[BE] Github 로그인 기능을 구현한다.

### ISSUE THREAD

**Issue by nailseong** [woowacourse-teams/2022-levellog#26]
## 목적
- 로그인 기능 이제는 해야한다.

## 작업 상세 내용
- [x] Github으로 로그인할 수 있다.

**Comment by SuyeonChoi** [comment]
## Member 테이블
|필드명|타입|세부정보|
|------|---|---|
|`id`|BIGINT|PK. Auto Increment|
|`nickname`|varchar(50)|크루 닉네임|
|`github_id`|Integer|Github 고유 아이디|
|`profile_url`|varchar(2048)|Github 프로필 이미지|

**Comment by kbsat** [comment]
## 테스트코드 작성에서 겪은 어려움
- 깃허브 로그인을 할 때 외부 깃허브 API로 호출을 하는 경우가 발생한다. 이를 어떻게 테스트해야 할지 고민이 된다.
- 현재 외부와 연동되는 부분을 제외하고 테스트는 완료한 상태이지만 아래 경우에 대해서는 아직 테스트를 진행하지 못했다.
  - 인수 테스트를 어떻게 작성할 것인가?
  - `GithubOAuthClient` 를 어떻게 테스트할지?
- 일단 일정 상 오늘까지 로그인 구현을 완료해야하기 때문에 해당 테스트를 제외하고 구현을 진행할 예정이다.

**Comment by kbsat** [comment]
### application-auth.yml 에 대한 고민
- 깃헙 로그인에 필요한 `Client-id`, `Client-secret` 과 Jwt 토큰의 `secret` 을 저장해놓은 설정 파일이 존재함.
- 해당 설정 파일이 깃헙에 올라오면 안되기 때문에 git ignore에 추가해두고 슬랙으로 공유중.
- 현재 팀에서 CI/CD를 하기 때문에 해당 auth 파일에 적어놓은 변수를 어떻게 배포서버에서 삽입할 것인가에 대한 고민 중
  - 환경 변수를 외부에서 삽입하는 방법이 있다고 함 ( 알린 )
  - 다른 크루의 이야기를 들으니 submodule 이란 것도 있다고 함.
