### ISSUE TITLE
[BE] 팀의 시작전/진행중/종료 상태를 반환하는 엔드포인트를 추가한다.

### ISSUE THREAD

**Issue by OzRagwort** [woowacourse-teams/2022-levellog#264]
## 목적
- 팀의 시작 상태를 확인하기 위해서

## 작업 상세 내용
- [x] 어떤 팀의 인터뷰 시작 상태(시작전, 진행중, 종료)를 반환하는 엔드포인트를 만든다.

## 참고사항
#236 #260 
위 이슈, PR이 먼저 머지가 되어야 할 것 같음.

**Comment by nailseong** [comment]
## API 스펙
`status`✅ 🆚 `statuses`
### Request
```http
GET /api/teams/1/status HTTP/1.1
Content-Type: application/json
Host: api.levellog.app
```

### Response
`READY`, `IN_PROGRESS`, `CLOSED`
```http
{
  "status" : "IN_PROGRESS"
}
```
