### ISSUE TITLE
[ALL] QA 시트를 제작한다.

### ISSUE THREAD

**Issue by SuyeonChoi** [woowacourse-teams/2022-levellog#283]
## 목적
QA 진행 시 누락되는 테스트가 없도록하기 위해 QA 시트를 제작하여 기본적인 틀을 잡는다. 

## 작업 상세 내용
- [x] QA 시트 제작한다.
- [x] 팀원들과 공유한다.

## 참고사항
- 프론트 1명, 백엔드 1명이 함께 작업하면 좋을 듯하다.
- [웹사이트 구축의 마지막 단계, QA를 진행해보자.](https://brunch.co.kr/@yuneuichoi/19)

**Comment by nailseong** [comment]
오~~ 굳아이디아~~~

**Comment by kbsat** [comment]
👍굳 아이디어~

**Comment by nailseong** [comment]
QA 시트 작성 후 노션에 공유했으므로 close합니다.
