### ISSUE TITLE
[BE] 레벨로그를 작성한 참가자를 팀 정보 수정으로 제외시키는 경우 레벨로그를 어떻게 할 것인가?

### ISSUE THREAD

**Issue by OzRagwort** [woowacourse-teams/2022-levellog#299]
## 목적
- 레벨로그를 작성한 참가자를 팀 정보 수정으로 제외시키는 경우 레벨로그를 `지운다` vs `그대로 둔다`
- 레벨로그를 그대로 둔다면 레벨로그에 적은 사전 질문을 `지운다` vs `그대로 둔다`

## 작업 상세 내용
- [ ] 토의 후 어떻게 할 지 결정할 듯

## 참고사항
https://github.com/woowacourse-teams/2022-levellog/pull/298#pullrequestreview-1072047708

**Comment by nailseong** [comment]
유지한다.
