### ISSUE TITLE
[BE] build.gradle의 프로젝트 버전을 수정한다.

### ISSUE THREAD

**Issue by OzRagwort** [woowacourse-teams/2022-levellog#304]
## 목적
- 현재 `0.0.1-SNAPSHOT`로 되어있는 버전을 우리 릴리즈 버전으로 수정한다.
- 소나큐브에서 저 버전으로 뜨길래 뭔가 거슬립니당 😃 

## 작업 상세 내용
- [ ] 버전 바꾸기

**Comment by SuyeonChoi** [comment]
@OzRagwort 어떤 네이밍으로 개선하고 싶으신가요?
