### ISSUE TITLE
[BE] 참관자 생성/수정 기능을 구현한다.

### ISSUE THREAD

**Issue by nailseong** [woowacourse-teams/2022-levellog#321]
## 목적
- 인터뷰에 인터뷰이로 참여하지 않고도, 피드백 작성 등이 가능해야한다. (e.g. 코치)

## 작업 상세 내용
- [x] 참관자 생성 기능
- [x] 참관자 수정 기능
- [x] 조회 수정
- [x] 참가자와 참관자는 중복되어 포함될 수 없다.
- [x] 호스트가 참가자 또는 참관자에 포함되지 않는 경우 예외를 던진다.
- [x] 참가자에 호스트가 무조건 포함되는 검증을 제거한다.
- [ ] [BE] `saveTeam()` Test Fixture를 수정한다.
- [x] 문서화
- [ ] [BE] Participant 도메인을 Unit으로 변경하고, `Watcher`과 `Participant`를 구분한다.

**Comment by SuyeonChoi** [comment]
- [ ] 참가자와 관전자는 중복되어 포함될 수 없다.
