### ISSUE TITLE
[BE] 예외 메세지에 대한 디버깅용 필드 삽입을 DebugMessage를 이용하도록 수정한다.

### ISSUE THREAD

**Issue by kbsat** [woowacourse-teams/2022-levellog#325]
## 목적
- 현재 예외 메세지를 만드는 형식이 달라 통일성이 없다.
- `DebugMessage`를 도입해 모든 형식을 변경하면 유지보수에 좋을듯 싶다.

## 작업 상세 내용
- [x] 모든 예외 메세지를 DebugMessage를 이용하도록 수정한다.
  - [x] Auth
  - [x] Member
  - [x] Levellog
  - [x] Feedback
  - [x] InterviewQuestion
  - [x] PreQuestion
  - [x] Team
  - [x] common
### AS-IS
**InterviewQuestion**
```java
    public void validateMemberIsAuthor(final Member member, final String errorMessage) {
        final boolean isNotAuthor = !author.equals(member);
        if (isNotAuthor) {
            throw new UnauthorizedException(
                    errorMessage + " 로그인 memberId : " + member.getId() + " 인터뷰 질문 작성자 memberId  : " + author.getId()
                            + " 인터뷰 질문 id : " + getId() + " levellogId : " + levellog.getId());
        }
    }
```

**UnauthorizedException**
```java
public class UnauthorizedException extends LevellogException {

    private static final String CLIENT_MESSAGE = "권한이 없습니다.";

    public UnauthorizedException(final String message) {
        super(message, CLIENT_MESSAGE, HttpStatus.UNAUTHORIZED);
    }
}
```

### TO-BE
**InterviewQuestion**
```java
    public void validateMemberIsAuthor(final Member member) {
        final boolean isNotAuthor = !author.equals(member);
        if (isNotAuthor) {
            throw new UnauthorizedException(DebugMessage.init()
                    .append("로그인 memberId", member.getId())
                    .append("인터뷰 질문 작성자 memberId", author.getId())
                    .append("인터뷰 질문 id", getId())
                    .append("levellogId", levellog.getId())
            );
        }
    }
```

**UnauthorizedException**
```java
public class UnauthorizedException extends LevellogException {

    private static final String CLIENT_MESSAGE = "권한이 없습니다.";

    public UnauthorizedException(final DebugMessage debugMessage) {
        super(CLIENT_MESSAGE, debugMessage, HttpStatus.UNAUTHORIZED);
    }
}
```

**Comment by nailseong** [comment]
## 커스텀 예외의 `clientMessage`는 상수화 합시다.
추가로 모든 커스텀 예외 클래스가 clientMessage를 상수로 갖고, 생성자를 통해서 clientMessage를 입력받지 않도록 변경하는 것에 대해서 논의하고 싶어요.
- `clientMessage`는 실제 http 응답으로 내려가는 예외여서 적당히 추상화가 되어도 문맥을 통해서 이해할 수 있기 때문에 상세하게 메시지를 적지 않아도 괜찮다.
- 추상화된 clientMessage + `DebugMessage`로 로그를 남기면 디버깅이 어렵지 않아 보인다.
- `service`, `entity`에 예외 메시지 관련 문자열이 코드의 가독성 & 유지보수를 저해시킨다.

저는 위와 같은 이유로 커스텀 예외에 `clientMessage`는 **모두 상수로 선언**하는게 좋아보입니다. `DebugMessage`와 잘 조합하면 시나지가 난다고 생각해요 😉

**Comment by SuyeonChoi** [comment]
릭, 로마 모두 좋은 의견인거 같아요. `DebugMessage`도입과 `clientMessage` 상수화를 반영하는 것 찬성합니다ㅎㅎ👍

해당 이슈는 리팩터링이라 나중에 바꾸기 힘들거 같고... 현재 통일성이 없긴 하지만 데이터를 부족하게 보내주는 것은 아니라서 급하지 않다고 생각했어요. 그래서 해당 이슈는 `#영종도🏝 스프린트`로 보내는건 어떨까요? 
혹시 급한 이슈인데 제가 놓친 부분이 있으면 코멘트 주세요!

레벨로그 서비스를 위해 끊임 없이 좋은 의견 주셔서 감사합니다🙇‍♀️🙇‍♀️🙇‍♀️

**Comment by 2yujeong** [comment]
InterviewTimeException이나 InvalidFieldException 같은 예외는 메시지를 추상화하기 어려워 보여요.
클래스를 분리하면 커스텀 파일이 너무 많아질 거 같고
메시지가 너무 추상화되면 프론트 입장에서 사용자 입력에 따른 예외를 처리할 때 애매할 수 있겠다는 생각이 드네요🤔 사용자 입장에서도 어떤 행동이 서비스 의도에 맞지 않는지 추상적이기 보다는 좀 더 구체적으로 알 수 있는 게 낫지 않을까요?

**Comment by kbsat** [comment]
### CIENT_MESSAGE 정리
- `XXXAlreadyExistException` : "XXX이(가) 이미 존재합니다."
- `XXXNotFoundException` : "XXX이(가) 존재하지 않습니다."
- `InvalidXXXException` : "잘못된 XXX 요청입니다."
- `DuplicateParticipantsExcetpion` : "중복되는 참가자가 존재합니다."
- `HostUnauthorizedException` : "호스트 권한이 없습니다."

### 작업 중 특이사항 정리
- ✅ `MemberNotFoundException`
  - 기존에 사용중이던 예외 중 호스트의 존재 유무를 확인하는 경우가 존재했음. ( CLIENT_MESSAGE = "멤버가 존재하지 않습니다" )
![스크린샷 2022-08-17 14 13 10](https://user-images.githubusercontent.com/52696169/185040009-eddca7d5-efc2-4995-9430-f2a4b4125069.png)
![스크린샷 2022-08-17 14 18 51](https://user-images.githubusercontent.com/52696169/185040538-cf050683-dacd-4c06-81a7-20300ed01862.png)
    - 방법 고민 중 해당 예외가 터지는 상황이 적다는 것을 판단 -> 예외를 억지로 붙인 느낌 -> orElseThrow() 로 그냥 커스텀 예외를 던지지 않고 디폴트 예외를 던져 500 Error가 뜨도록 수정 
 
- `InterviewTimeException`
  - team 생성자 : "InterviewTime은 현재 시간 이후여야합니다." -> 필드로 삽입하기 위해 검증하는 예외이므로 `InvalidFieldException` 으로 수정
  - team update : "인터뷰가 시작된 이후에는 수정할 수 없습니다."
  - team delete : "인터뷰가 시작된 이후에는 삭제할 수 없습니다."
  - team close : "인터뷰가 시작되기 전에 종료할 수 없습니다." 
  - team close : "이미 종료된 인터뷰입니다." -> InterviewTime과는 관계가 멀어 보이기 때문에 `AlreadyClosedException` 으로 변경
  - feedback save : "인터뷰가 시작되기 전에 피드백을 작성할 수 없습니다."
  - feedback update : "인터뷰가 시작되기 전에 피드백을 수정할 수 없습니다."
  - interviewQuestion save : "인터뷰 시작 전에 인터뷰 질문을 작성 할 수 없습니다."
  - interviewQuestion update : "인터뷰 시작 전에 인터뷰 질문을 수정 할 수 없습니다."
  - interviewQuestion delete : "인터뷰 시작 전에 인터뷰 질문을 삭제 할 수 없습니다."
  - levellog save : "인터뷰 시작 전에만 레벨로그 작성이 가능합니다."
  - levellog update : "인터뷰 시작 전에만 레벨로그 수정이 가능합니다."

- 시작 전에만 가능 -> `TeamNotReadyException`
  - Team update, Team delete
  - Levellog save, Levellog update
- 시작 후에만 가능 -> `TeamNotInProgressException`
  - Team close
  - Feedback save, Feedback update
  - InterviewQuestion save, InterviewQuestion update, InterviewQuestion delete

- `UnAuthorizedException`
  - 해당 예외는 권한이 없는 예외를 나타내었었음.
  - 보통 팀의 참가자가 아닌 경우, 내가 작성한 글이 아닌 경우 두 경우가 있어서 이를 구체화하여 Client_message를 공유하도록 했음.
  - `MemberNotAuthorException` : 멤버가 작성자가 아닌 경우 발생하는 예외
    - InterviewQuestion : delete, update
    - Levellog :  update
    - PreQuestion : delete, update
  - `ParticipantNotSameTeamException` : 팀의 참가자가 아닌 경우 발생하는 예외
    - Team : findMyRole
    - Feedback : save, findById, findAll
    - InterviewQuestion : save
    - PreQuestion : save
