### ISSUE TITLE
[BUG] 팀 participants가 무작위 순서로 바뀌는 버그 수정

### ISSUE THREAD

**Issue by frontend-jihyeok-um** [woowacourse-teams/2022-levellog#434]
## 버그 기능
- 같은 팀이라도 participants가 무작위 순서로 바뀌는 버그가 있음 (전체 팀 조회에서)

#### 처음
<img width="821" alt="스크린샷 2022-09-19 오후 7 04 01" src="https://user-images.githubusercontent.com/75592315/190994584-2c65415c-1e79-475c-96b0-14949aa1b384.png">

#### 새로고침
<img width="862" alt="스크린샷 2022-09-19 오후 7 04 08" src="https://user-images.githubusercontent.com/75592315/190994590-b2da7852-9839-4052-9474-c9cc22c91292.png">

### 기대 동작
- 팀 참가자 순서 보장

### 현재 동작
- 팀 참가자 순서 보장 X

**Comment by nailseong** [comment]
#452
