### ISSUE TITLE
[FE] 웹 접근성을 준수한다. 

### ISSUE THREAD

**Issue by byhhh2** [woowacourse-teams/2022-levellog#493]
## 목적

웹 접근성 향상을 위한 피드백입니다. 😎

(💚 속닥속닥 팀이 놀러왔어용 ~ 방가방가 🛫👋)

## 작업 상세 내용

- 아이콘에서 svg 파일명을 읽어줘서 불편합니다. 
- 검색 버튼이 왼쪽에 존재해서 불편합니다. (보통 오른쪽에 검색버튼이 있고, 왼쪽 돋보기는 아이콘 아닌가요?)
- 레벨로그 보기를 불렀을 때 탭이 모달 밖도 포커스 가능해서 닫는데 시간이 오래 걸립니다. 
- 탭으로 로그아웃이 불가능합니다.

**Comment by JUDONGHYEOK** [comment]
### 추가 내용
- 레벨로그 보기를 하면 관련질문보기에 누구의 것인지도 읽어주면 좋을 것 같습니다
- 팀추가하기까지 탭으로 접근하기가 너무 멀어요 조금 땡기면 좋을 것 같습니다
