### ISSUE TITLE
[FE] 메인페이지 로고를 진돌이로 변경한다.

### ISSUE THREAD

**Issue by SuyeonChoi** [woowacourse-teams/2022-levellog#510]
## 목적
진돌이가 탄생하였습니다. 변경해주세요.

## 작업 상세 내용
- [ ] 파비콘을 진돌이로 변경한다

## 참고사항
귀여운 진돌이
![제목_없는_아트워크 2](https://user-images.githubusercontent.com/28749734/196344515-8fde3e3c-e50c-47a5-8f9a-9c5479f898d7.png)

**Comment by nailseong** [comment]
@yunjin-kim 
해줘잉~~~

**Comment by yunjin-kim** [comment]
왈와왈왈ㅇㅇ왈ㅇ왈알앙알알 컹컹ㅋㅇ컼엉컹
