### ISSUE TITLE
[BUG] 팀 상세 조회시 참가자가 정렬되지 않는 문제를 해결한다.

### ISSUE THREAD

**Issue by nailseong** [woowacourse-teams/2022-levellog#522]
## 버그 기능
- 팀 상세 조회시 참가자 정렬 상태가 보장되지 않는다.

### 버그 상황 재연
- 팀 상세 조회 화면에서 간헐적으로 참가자 순서가 흐트러진다.
- 해당 버그는 로그인 여부에 상관없이 발생한다.

### 기대 동작
- 생성 순서를 지켜서 참가자를 응답해야한다.

### 현재 동작
- 생성 순서를 지켜서 응답하지 않는다.
- 단, 뒤죽박죽으로 섞이지는 않는다.
![스크린샷 2022-10-19 오후 8 23 13](https://user-images.githubusercontent.com/68512686/196677590-4678e91b-2bf8-4b93-95c6-05d3fa206799.png)
![스크린샷 2022-10-19 오후 8 23 50](https://user-images.githubusercontent.com/68512686/196677703-328412b5-891d-4b5c-8eb8-4431aa94c631.png)

**Comment by kbsat** [comment]
의심점
생성 , 쿼리 , 조회
- [x] 생성 체크
- [ ] 쿼리 체크
- [x] 조회 로직 체크

**Comment by nailseong** [comment]
문제는 쿼리였습니다.

테스트 코드 추가 PR과 함께 close하겠습니다.

**Comment by nailseong** [comment]
아래와 같은 이유로 테스트 코드 추가 없이 close합니다.
- 동시성 이슈는 테스트 코드로 검증하기 어렵다.
- CI에서 테스트 결과의 일관성을 보장하지 않는다. (실행시키는 머신의 성능에 따라 달라진다.)
