### ISSUE TITLE
[BUG] 사전질문 수정시 원래 사전질문이 Ref에 없는 버그를 수정한다.

### ISSUE THREAD

**Issue by frontend-jihyeok-um** [woowacourse-teams/2022-levellog#526]
## 버그 기능
- 사전질문 수정버튼을 눌러 사전질문 수정페이지로 갔을 때, 기존에 작성했던 사전질문이 Ref에 나타나지 않는다.
- 테스트 서버에서만 발생한 버그입니다.

![스크린샷 2022-10-19 오후 10 01 38](https://user-images.githubusercontent.com/75592315/196698319-26a8d475-3e0a-40f2-95f9-14bbedb58d20.png)

![스크린샷 2022-10-19 오후 10 01 44](https://user-images.githubusercontent.com/75592315/196698357-03feae84-71ad-43aa-b58f-2091a633d17f.png)

**Comment by yunjin-kim** [comment]
https://github.com/woowacourse-teams/2022-levellog/pull/518

이거 pr에서 수정해서 close할게용
