### ISSUE TITLE
[FE] 인터뷰 팀 기능을 구현한다.

### ISSUE THREAD

**Issue by yunjin-kim** [woowacourse-teams/2022-levellog#55]
## 목적

- 레벨로그 팀 기능을 도입하기 위해

## 작업 상세 내용

- [x] #59 
- [x] #61
- [x] #63
- [x] #64

**Comment by SuyeonChoi** [comment]
도메인명을 그룹 -> 팀으로 변경했으니 이슈 타이틀도 업데이트할게요!🙂
