### ISSUE TITLE
[BE] 팀 CRUD를 구현한다.

### ISSUE THREAD

**Issue by 2yujeong** [woowacourse-teams/2022-levellog#56]
## 목적
팀 기능을 도입한다.

## 작업 상세 내용
- [x] #57
- [x] #58
- [x] #60
- [x] #62

**Comment by SuyeonChoi** [comment]
도메인명을 바꾸면서 이슈 타이틀도 그룹 -> 팀으로 수정합니다~!

## 작업 상세 내용
- [x] 팀 생성 API
- [x] 팀 목록 조회 API
- [x] 팀 상세 조회 API
- [x] 팀 수정 API
- [x] 팀 삭제 API

## 추가 작업
- [x] 인수테스트 작성
- [x] 테스트에서 인증 적용
- [x] Spring Rest Docs 적용
