### ISSUE TITLE
[BUG] 최신에 작성한 피드백이 아래로 가는 버그를 수정한다.

### ISSUE THREAD

**Issue by frontend-jihyeok-um** [woowacourse-teams/2022-levellog#567]
## 버그 기능
- [ ] 최신에 작성한 피드백이 아래로 가는 버그를 수정한다.

### 버그 상황 재연
- test까지 버그가 발생중입니다
- 아마 1.4.6까지는 괜찮았던 것 같은데, 1.4.7부터 포함된 버그라면 지금 운영서버도 동일한 버그가 발생할 것 같습니다.

![스크린샷 2022-11-01 오후 7 09 51](https://user-images.githubusercontent.com/75592315/199216911-7eeb01fa-1377-486a-8624-9630c266ddcb.png)

**Comment by OzRagwort** [comment]
지금 문제가 발생한다면 1.4.6 이전부터 발생하던 문제 같아요 QA가 부족했던 것 같습니다ㅠ
