### ISSUE TITLE
[BUG] 존재하지 하지 않는 레코드에 비관적 락을 거는 로직을 수정한다.

### ISSUE THREAD

**Issue by nailseong** [woowacourse-teams/2022-levellog#593]
## 버그 기능
- #534 에서 해결한 줄 알았던 비관적 락으로 존재하지 않는 레코드 잠금 걸기 방법이 동작하지 않음
- 당시 잠금이 걸렸던 상황은 잠금을 획득하는 쿼리가 아래와 같았기 때문이다.
  ```sql
  SELECT l.id 
  FROM levellog l
	  LEFT OUTER JOIN team t ON l.team_id = t.id
  WHERE l.author_id = ? AND t.id = ?
  LIMIT 1 FOR UPDATE;
  ```
- 실행 계획에서 team 테이블에 먼저 점근한다. 즉 id에 해당하는 팀이 존재하면 해당 team 레코드에 쓰기 잠금을 먼저 건다. 그 후 levellog 테이블에서 team_id가 일치하는 모든 레벨로그에 잠금을 건다.
- 만약 조회 결과가 존재하지 않아도 team 레고드에 먼저 잠금이 걸리기 때문에 다른 트랜잭션은 대기 상태에 빠지게 된다. 따라서 잠금이 우리의 의도와 다르게 걸린다.
  ![스크린샷 2022-11-09 오후 10 23 03](https://user-images.githubusercontent.com/68512686/200841467-ff2ee05a-62b5-4ce2-8429-9b6167062aeb.png)

### 버그 상황 재연
- 존재하지 않는 레코드에는 잠금을 걸 수 없다.

### 기대 동작
- team_id와 author_id가 일치하는 레코드에 대해서 동시에 여러 트랜잭션이 쓰기를 하지 못하도록 한다.

**Comment by nailseong** [comment]
UNIQUE 제약 조건을 걸거나 named lock으로 해결해야 할 듯?

**Comment by kbsat** [comment]
해당 상황을 지속할 경우 데드락의 우려가 있습니다 ㅜ.ㅜ

1. `A 트랜잭션`에서 없는 레코드에 대해 락을 건다. ( 우리가 원하는 레코드 락이 아닌 갭락이 걸린다. )
2. `B 트랜잭션`에서 없는 레코드에 대해 락을 건다. ( 우리가 원하는 레코드 락이 아닌 갭락이 걸린다. 갭락의 경우 다른 락과 달리 공존이 가능하므로 `A 트랜잭션`과 함께 락을 걸 수 있다. )
3. `A 트랜잭션`이 insert 를 한다 ( 하지만 `B 트랜잭션`이 건 갭락에 의해 인서트가 막힌다. )
4. `B 트랜잭션`이 insert 를 한다. ( `A 트랜잭션`이 건 갭락에 의해 인서트가 막힌다. )
5. 결국 데드락!
6. Innodb Deadlock 감지로 상황종료
