### ISSUE TITLE
[FE] 프론트엔드 초기 환경을 구성한다.

### ISSUE THREAD

**Issue by yunjin-kim** [woowacourse-teams/2022-levellog#7]
## 목적

레벨로그 프론트엔드 개발을 위한 환경설정

## 작업 상세 내용

- Webpack
- Babel
- React
    - Context API
- TypeScript
- Eslint
- Prettier
- styled-components
- Storybook
- Jest

**Comment by OzRagwort** [comment]
밑에 간단하게 설명 적어주실 수 있나요 🥲

**Comment by yunjin-kim** [comment]
https://github.com/woowacourse-teams/2022-levellog/issues/7#issuecomment-1175664979

Webpack : JS, CSS, HTML 등의 파일들을 하나이상의 파일로 압축해주는 모듈
Babel : 자바스크립트 하위 호환 버전으로 변환시켜주는 툴체인, 자바스크립트 컴파일러
React : UI를 만들기 위한 자바스크립트 라이브러리
Context API : 전역에서 데이터를 가지고 React앱 어디서든 편하게 전달할 수 있게 해주는 모듈
TypeScript : 타입 및 추가적인 구문을 제공하는 자바스크립트 슈퍼셋
Eslint : 코드 오류를 잡아주는 모듈
Prettier : 코드 컨벤션을 지켜주는 코드 포멧터
styled-components : 리액트 컴포넌트 시스템에서 css를 더 잘 쓰기 위한 모듈
Storybook : UI 개발할 때 개발한 컴포넌트들을 명시적으로 보여주기 위한 모듈
Jest : 자바스크립트 테스팅 프레임워크

**Comment by yunjin-kim** [comment]
> 밑에 간단하게 설명 적어주실 수 있나요 🥲

Webpack : JS, CSS, HTML 등의 파일들을 하나이상의 파일로 압축해주는 모듈
Babel : 자바스크립트 하위 호환 버전으로 변환시켜주는 툴체인, 자바스크립트 컴파일러
React : UI를 만들기 위한 자바스크립트 라이브러리
Context API : 전역에서 데이터를 가지고 React앱 어디서든 편하게 전달할 수 있게 해주는 모듈
TypeScript : 타입 및 추가적인 구문을 제공하는 자바스크립트 슈퍼셋
Eslint : 코드 오류를 잡아주는 모듈
Prettier : 코드 컨벤션을 지켜주는 코드 포멧터
styled-components : 리액트 컴포넌트 시스템에서 css를 더 잘 쓰기 위한 모듈
Storybook : UI 개발할 때 개발한 컴포넌트들을 명시적으로 보여주기 위한 모듈
Jest : 자바스크립트 테스팅 프레임워크
