### ISSUE TITLE
[ALL] 지금 우리의 브랜치 전략. 이대로 괜찮은가?

### ISSUE THREAD

**Issue by OzRagwort** [woowacourse-teams/2022-levellog#71]
## 목적
- 지금 우리의 브랜치 전략이 조금 이상한 것 같음.
  - 이슈를 조금 크게 묶어서 열고, 이슈 단위로 브랜치를 파고 그곳에 스쿼시 머지. 최종 완료가 되면 main에 머지하는 방식이 어떤가 싶음.
  - develop 브랜치를 파는건 그렇다고 해도, 최소한 이슈 단위에 대한 이야기는 해봤으면 좋겠음
- 지금 Team 도메인을 예로들면 BE와 FE 합쳐서 총 10개의 이슈가 생기는데 이걸 1개의 이슈로 만든 뒤 develop/team 브랜치 생성.
  - BE에서 구현하고 develop/team 브랜치에 스쿼시 머지를 함.
  - FE에서 구현/수정 된 코드로 구현하여 develop/team 브랜치에 스쿼시 머지를 함.
  - Team 도메인과 관련된 기능이 모두 완성되면 main에 머지하여 기능을 추가하고 이슈를 닫음.
- 이렇게 하려는 이유
  - 지금은 이슈가 불필요하게 많아짐.
  - BE에서 API를 수정하고 바로 main에 배포하면 FE의 수정된 코드가 배포되기 전까지 FE 페이지에서 그 기능은 되던게 안되게 됨.
  - `Github Flow는 빠르게 기능을 추가하여 배포할 수 있다는 장점이 있다.` -> 기능의 단위를 다시 고민해보고 싶음.

## 작업 상세 내용
- [x] 브랜치 전략에 대해 이야기 해보기
- [x] 수정 하기 or 유지 하기 결정

## 참고사항

#70

**Comment by 2yujeong** [comment]
develop 브랜치 전략 도입
