### ISSUE TITLE
[ALL] main 브랜치에 직접 push 하지 못하도록 설정한다.

### ISSUE THREAD

**Issue by OzRagwort** [woowacourse-teams/2022-levellog#8]
## 목적
main 브랜치에 직접 푸쉬하지 못하도록 하기 위함

## 작업 상세 내용
Settings - Code and automation - Branches - main 에서 두가지 설정을 해야 함

- [x] Require a pull request before merging -> Require approvals 설정
    - 최소 approve 수를 설정하여 직접 푸쉬하지 못하도록 함
- [x] Include administrators
    - admin 권한이어도 위 설정이 적용되도록 함

**Comment by nailseong** [comment]
브랜치 보호 규칙
- https://2ndprince.tistory.com/49
